name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  unix:
    runs-on: ${{ matrix.cfg.os }}
    defaults:
      run:
        working-directory: ci
    strategy:
      matrix:
        cfg:
          - {os: ubuntu-latest, btype: Debug, cmakeflags: "-DYNAMIX_ASAN=1", buildflags: "-- -j"}
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Configure
        run: cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.cfg.btype }} ${{ matrix.cfg.cmakeflags }}
      - name: Build
        run: cmake --build . --config ${{ matrix.cfg.btype }} ${{ matrix.cfg.buildflags }}
      - name: Test
        run: ctest -C ${{ matrix.cfg.btype }} --output-on-failure
